### ISSUE TITLE
Do we need to use prebid universal creative?

### ISSUE THREAD

**Issue by salvoaranzulla** [prebid/prebid-universal-creative#109]
We erogate only display banner on our website without AMP and without SafeFrame. We are using right now the legacy rendering code:

`<script>
var w = window;
for (i = 0; i < 10; i++) {
  w = w.parent;
  if (w.pbjs) {
    try {
      w.pbjs.renderAd(document, '%%PATTERN:hb_adid%%');
      break;
    } catch (e) {
      continue;
    }
  }
}
</script>`

If I read the code of https://github.com/prebid/prebid-universal-creative/blob/master/src/renderingManager.js, I see that In my case the script erogates the legacy code:

`    if (environment.isMobileApp(targetingData.env)) {
      renderAmpOrMobileAd(targetingData.cacheHost, targetingData.cachePath, targetingData.uuid, targetingData.size, targetingData.hbPb, true);
    } else if (environment.isAmp(targetingData.uuid)) {
      renderAmpOrMobileAd(targetingData.cacheHost, targetingData.cachePath, targetingData.uuid, targetingData.size, targetingData.hbPb);
    } else if (!environment.canLocatePrebid()) {
      renderCrossDomain(targetingData.adId, targetingData.adServerDomain, targetingData.pubUrl);
    } else {
      renderLegacy(doc, targetingData.adId);
    }`

Do we need to use prebid universal creative? Are there any benefit to use prebid universal creative instead legacy rendering code in our case?

**Comment by bretg** [comment]
If you're not using safeframes, AMP, mobile, or native, then a direct call to pbjs.renderAd is fine.

I'll leave this open until we document this on prebid.org somewhere. There ought to be a page that talks more about PUC in general, including other load options some pubs may wish to consider.

**Comment by bretg** [comment]
The docs page at https://docs.prebid.org/overview/prebid-universal-creative.html was updated with alternate approaches to the PUC.
