### ISSUE TITLE
Load-Cookie: support passing AMP consent strings

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-universal-creative#114]
With the current amp-iframe approach, it's not possible to obtain GDPR consent strings and pass them through load-cookie.html. So AMP-originated calls to Prebid-Server's /cookie_sync endpoint will never contain GDPR consent data.

This is obviously a problem -- it causes every /cookie_sync to fail for users in the EEA.

Passing GDPR consent strings through AMP iframes isn't currently possible. As of this writing the AMP PR is in-progress -- https://github.com/ampproject/amphtml/pull/29636 isn't merged.

But even when it is merged, our amp-iframe implementation is going to require work. Instead of the nice simple <amp-iframe src=load-cookie.html> approach, we're going to need to be more dynamic because the iframe needs to post a message to get consent data and parse the results.

Here's a proposed approach:

1. amp-iframes can load a new (optional) version of load-cookie.html (e.g load-cookie-with-consent.html)
2. This new file takes all the same parameters as load-cookie.html
3. But it also contains javascript that polls the CMP for results
4. when it gets results, it parses the consent string and dynamically generates the call to PREBID-SERVER
5. drop the pixel to PREBID-SERVER

**Comment by bretg** [comment]
The AMP PR has been merged -- this issue is unblocked.

**Comment by bretg** [comment]
@klipstein - the I2I you opened on the AMP project - does that mean that the proposed solution above won't work?

**Comment by klipstein** [comment]
@bretg sorry for the confusion. The above solution would work because you now can read the consent-string within `<amp-iframe>`. I just wanted to refer to this use-case, where standard-postmessage-TCF-2.0 reading would probably be sufficient or is already in place.

**Comment by bretg** [comment]
Implemented with the load-cookie-with-consent.html file described in https://docs.prebid.org/dev-docs/show-prebid-ads-on-amp-pages.html#user-sync
