### ISSUE TITLE
utils.triggerBurl is not defined

### ISSUE THREAD

**Issue by GeneGenie** [prebid/prebid-universal-creative#116]
From the code it seemed like adresponse format for universal creative ( in AMP context) supports burl. 
But [utils.triggerBurl](https://github.com/prebid/prebid-universal-creative/blob/40b352d97e6c863b401a57b69db9ef76f7223784/src/renderingManager.js#L219) is not defined in utils 

Secure creative v1.8.0

**Comment by patmmccann** [comment]
Appears fixed https://github.com/prebid/prebid-universal-creative/blob/99d4c0ee79fb49aefcf1e3a6798994855968ac5a/src/renderingManager.js#L238
