### ISSUE TITLE
Possible resize issue on AMP

### ISSUE THREAD

**Issue by muotaz** [prebid/prebid-universal-creative#119]
Hello 

I am not sure if this an actual bug in the universal creative or in AMP runtime, but I hope that you could shed some light on this to be able to better understand the issue and solve it afterwards.

We have noticed on websites that use amp-ad element with multisize property, that the resize request issued by the universal creative to the AMP runtime is being requested more frequently.
Our observations indicate that the resize request is rejected when there is a change in the width and the height of the amp-ad element (here: https://github.com/prebid/prebid-universal-creative/blob/f062693ed8ce4d4faf1b9641da12c2f4990c6ee4/src/renderingManager.js#L280).

A simple test, where a modified universal creative that eliminates any change in the width, greatly mitigates this issue:
```
    var f = s.split("x").map(Number);
                    !function(n, o) {
                        if (d.isSafeFrame()) {
                            var i = h.innerWidth
                              , a = h.innerHeight;
                            i === n && a === o || (h.$sf.ext.register(n, o, function(t) {
                                var e = n - i
                                  , r = o - a;
                                  console.log("t ", t, "sizes:", e,"x",r);
                                  if(e<0) {
                                      e=0;
                                      console.log("e is reset");
                                  }
                                h.$sf.ext.expand({
                                    r: e,
                                    b: r,
                                    push: !0
                                })
                            }),
                            console.log("t ", t, "sizes:", n,"x",o),
```

I appreciate your opinion on this regard.

**Comment by premesh-freestar** [comment]
Are u using safe frames for the the creative ? Im running into the same issue here. Looking into the UC code i see this 
https://github.com/prebid/prebid-universal-creative/blob/f062693ed8ce4d4faf1b9641da12c2f4990c6ee4/src/renderingManager.js#L268

makes it seem like safeframes are required for AMP ?

**Comment by jsnellbaker** [comment]
@robertrmartinez Could you take a look into this please?

**Comment by andyblackwell** [comment]
I just tested this on our setup with multisize and safeframe off, and can confirm all the prebid wins are rendering at size 1x1

**Comment by premesh-freestar** [comment]
So perhaps there is no issue? Just need to use safe frames since UC expects amp to uses the amp apis to resize the container?

**Comment by muotaz** [comment]
We are already using safe frame. The issue is that sometimes AMP runtime denies the resize request when there is a difference in both width and height.
And indeed we are using multisize with safeframes.

**Comment by premesh-freestar** [comment]
Ok so I did see a few times the resize seemed to fail however if I tabbed
away and back it would fire.. Almost seemed like the called queued and amp
runtime was waiting for the opportunity to do the change?

**Comment by muotaz** [comment]
Yes I also noticed that, the calls for the resize piled up but AMP was almost always rejecting them.
With this change, the resize request fails a couple of times before being executed when the ad is out of the viewport.
The master creative there is 320x50 in size. 
Would changing it to 1x1 resolve the issue ?

**Comment by bretg** [comment]
@muotaz - is this still an issue for you?

Do you think it might help if the PUC did **two** resize calls - one for the height and one for the width. (?)

**Comment by muotaz** [comment]
Hello @bretg 

Wow, quite a lot of time has passed since that! 
I don't think we have had that issue since the time we reported this. 
Let me check with our Adops dept and I will get back to you with info if this issue is still relevant. 

Thanks!

**Comment by patmmccann** [comment]
@muotaz any luck confirming? Thanks!

**Comment by muotaz** [comment]
Hello @patmmccann 
Seems like this is no longer an issue, I will close this and reopen if this happens again.
Thanks alot!

**Comment by GeneGenie** [comment]
Confirming this is still happening. I think that issue is double resizing. eg: amp-ad   has size preset of 300x250, when pbjs creative is loaded AMP resizes container to 1x1 (i suppose AMP does this), and following resize/expand request stays in some amp-reflow queue until window is resizes, or tab switched.
