### ISSUE TITLE
npm install fails with node v12

### ISSUE THREAD

**Issue by ReinoutStevens** [prebid/prebid-universal-creative#120]
**Describe the bug**
npm i fails with node v12

You get a large list of errors like:
../src/fibers.cc:68:2: error: ‘Handle’ does not name a type

The suggested solution is to install g++ build essentials, which were already present.

**To Reproduce**

* remove node_modules ( or get a fresh copy of this repo )
* use node v12 ( tested with v12.17.0 and v12.18.4 )
* npm i

**Expected behavior**
Expect everything to get installed :)

**Desktop (please complete the following information):**
 - OS: Ubuntu 2020.04

**Additional context**
Using Node v10 works fine, and after installing you can just switch to node v12 without any issue

**Comment by GLStephen** [comment]
Try deleting your package-lock and using 'npm ci'.

**Comment by ReinoutStevens** [comment]
I assume you mean deleting your node_modules, and doing `npm ci`, as deleting your package-lock is not appreciated by npm ci.

Same error persists in this case.

**Comment by GLStephen** [comment]
@ReinoutStevens yeah

1. rm ./package-lock.json
1. git checkout package-lock.json
1. npm ci

**Comment by ReinoutStevens** [comment]
Yeah thats what I did after `npm ci` complained that it requires a package-lock file :)
Fails both on master and 1.8.0

**Comment by dgirardi** [comment]
This should be fixed by https://github.com/prebid/prebid-universal-creative/pull/159
