### ISSUE TITLE
Support arbitrary PBS endpoints

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-universal-creative#122]
Currently load-cookie.html only supports 'appnexus' and 'rubicon' endpoints. It's unfriendly for other PBS hosts to have to modify the cookieSync.js script.

Here's what the load-cookie invocation looks like:

```
https://PROVIDED_BY_HOSTCOMPANY/load-cookie.html?endpoint=HOSTCOMPANY
```

The proposal here is that we expand the values that the 'endpoint' parameter can accept:
- appnexus
- rubicon
- a url-encoded PBS URL. e.g. https%3A%2F%2Fprebid-server.example.com%2Fcookie_sync

validations:
- if the endpoint is not on the VALID_ENDPOINTS object, it must start with https

**Comment by premesh-freestar** [comment]
perhaps its better to have the "endpoint"  value be `custom` and then support an additional optional param to pass the end point url. Further not that it matters but should we care if the url doesnt have cookie_sync in it ? if it loads the sync correctly it should be fine either way ?

**Comment by bretg** [comment]
Dropped the cookie_sync validation. I don't feel strongly about this interface. If you write the code, it can be whatever way you prefer. :-)

**Comment by bretg** [comment]
This was fixed in the PUC load-cookie.html a while back. Just documented the usage on https://docs.prebid.org/dev-docs/show-prebid-ads-on-amp-pages.html#user-sync
