### ISSUE TITLE
Ad markup with <!DOCTYPE html> fails to render on mobile

### ISSUE THREAD

**Issue by rokostik** [prebid/prebid-universal-creative#134]
**Describe the bug**
If an ad markup contains the `<!DOCTYPE html>` preamble, the prescribe library (which postscribe uses to parse HTML: https://github.com/krux/prescribe) fails to parse the preamble and silently stops parsing and only the HTML up to that point is inserted into the document. This is a know and old issue with postscribe (https://github.com/krux/postscribe/issues/358). 

**To Reproduce**
From prebid server return any ad markup with `<!DOCTYPE html>` (eg. `<!DOCTYPE html><p>test<p>`) and inspect the DOM in chrome://inspect.
In my case I only see the  comment and two additional divs that are made, but not the ad markup. 
Removing the doctype preamble renders the ad as expected.

**Expected behavior**
Render the ad with doctype correctly as on the web with prebid.js.

**Screenshots**
Render if doctype included:
<img width="596" alt="Screenshot 2021-03-19 at 11 21 34" src="https://user-images.githubusercontent.com/9090706/111766589-ff59f900-88a5-11eb-9294-1ca2f4daae6f.png">

Render without doctype:
<img width="593" alt="Screenshot 2021-03-19 at 11 23 10" src="https://user-images.githubusercontent.com/9090706/111766248-9a060800-88a5-11eb-84e7-24bbd1563b17.png">

**Smartphone:**
Tested on the android emulator.

**Comment by bretg** [comment]
Can you recommend a solution to this issue @rokostik ?   

@YuriyVelichkoPI - could you take a look?

**Comment by patmmccann** [comment]
It seems we just strip that line using a regex before this line? https://github.com/prebid/prebid-universal-creative/blob/4066462427c1026b55092fb941cc71895881bf5e/src/utils.js#L35

**Comment by patmmccann** [comment]
It appears https://github.com/krux/postscribe/pull/507/files may also solve ; @nickjacob could you comment?

**Comment by nickjacob** [comment]
Hi @patmmccann  -- that's true, our fork of prescribe skips over invalid/unrecognized HTML; this is the relevant commit -- https://github.com/AppMonet/prescribe/commit/cfc81a3d541ffa4e6a4f9512207f4f89827dbcec

We've used it a lot in mobile app environments, but it doesn't have great test coverage. I'm not currently using it (we just build an additional iframe & contentDocument.write when rendering asynchronously).

**Comment by nickjacob** [comment]
I can clean up my prescribe & postscribe forks and publish to NPM if you want to test the behavior on this

**Comment by nickjacob** [comment]
@patmmccann looks like you're right -- https://jsfiddle.net/76xcq12d/ the @appmonet/postscribe does handle the doctype in the ADM

I made a PR to prescribe with only the change that would fix this. Not sure if you want to go off of our fork? Looks like smaato also has a fork with some good changes. I just published @appmonet/postscribe to NPM, you could try it in universal creative like this:

`"postscribe": "npm:@appmonet/postscribe@0.1.2"`

So the import doesn't have to change

**Comment by dgirardi** [comment]
I am unable to reproduce, but I'm afraid I'm missing some context. I tried rendering the example markup (`<!DOCTYPE html><p>test<p>`), through "normal" prebid.js & PUC  in an emulated android webview, and it renders correctly. What is the setup here - as far as PUC is concerned I believe it should be enough to set it up as per the [prebid-mobile instructions](https://docs.prebid.org/prebid-mobile/adops-line-item-setup-dfp.html), is there something else different about mobile?

**Comment by dgirardi** [comment]
Looking through the code, it appears that setting up ads for mobile is more complicated than I can afford, and not documented (at least not [here](https://docs.prebid.org/prebid-mobile/adops-line-item-setup-dfp.html)), which explains why it was not seeing the issue. If I force use of postscribe rendering does fail, and https://github.com/prebid/prebid-universal-creative/pull/172 seems to fix it.

However this raises the question: why are we using postscribe? ads rendered "normally" seem to work fine in an android webview. It's also useless bytes for everyone not serving mobile ads. Is it a relic of the past?
