### ISSUE TITLE
PUC Installation Error

### ISSUE THREAD

**Issue by GenarC** [prebid/prebid-universal-creative#155]
Description:
On PUC installation, getting install errors. I'm doing exacly the readme file says.
![image](https://user-images.githubusercontent.com/20942609/153006563-0a22b003-69c1-4d02-bf1a-ed5d803006bc.png)

To Reproduce:
1. Cloned the repo into ../var/prebid/prebid-unşversal-creative
2. Installed npm
3. Installed gulp
4. Went into the repository directory
5. run "npm install"

Expected behavior:
I want to serve my own prebid server-cache-universal creative. So I need to install PUC.

**Screenshots**
![image](https://user-images.githubusercontent.com/20942609/153006563-0a22b003-69c1-4d02-bf1a-ed5d803006bc.png)

Desktop (please complete the following information):
 - OS: CentOS 8

How can I fix this problem?

**Comment by bretg** [comment]
@GenarC - I suspect it's a node/npm version thing.  The install works for me with node 11.5 and npm 6.4.1

>$ nvm use 11.5.0
>Now using node v11.5.0 (npm v6.4.1)

**Comment by dgirardi** [comment]
This should be fixed by https://github.com/prebid/prebid-universal-creative/pull/159
