### ISSUE TITLE
Remove postscribe dependency

### ISSUE THREAD

**Issue by patmmccann** [prebid/prebid-universal-creative#179]
We'd like to identify why the postscribe dependency exists, and if possible, remove it for either web or all of PUC depending on the genesis.

**Comment by bretg** [comment]
We need someone to document what actually is postscribe. Ideally, we should also at least try to hypothesize why it might have been added to the PUC.

**Comment by dgirardi** [comment]
To answer: why was it added in the first place? was it for performance reasons on mobile webviews?
