### ISSUE TITLE
Native ads do not trigger `AD_RENDER_SUCCEEDED` / `AD_RENDER_FAILED`

### ISSUE THREAD

**Issue by dgirardi** [prebid/prebid-universal-creative#182]
**Describe the bug**

Rendering a native ad does not trigger the AD_RENDER_SUCCEEDED & FAILED event like banner ads do.

**To Reproduce**

Render any ad through the PUC `native-render.js`.

**Comment by patmmccann** [comment]
Aside: succeeded is rather misleading, we may want to rename 'attempted' or similar
