### ISSUE TITLE
Prebid Native Universal Creatives not tracking all clicks (aux clicks)

### ISSUE THREAD

**Issue by chakersaloumi** [prebid/prebid-universal-creative#198]
Hi Team,

Some publishers are raising that the prebid native universal creative is not tracking clicks when the user presses on the mouse wheel or right clicks and then "new tab". Is this expected?
Please see this test page showing when the creative identifies a click action:
https://advideo.uimserv.net/stek/native_clicks/page.html

Best,
Chaker

**Comment by dgirardi** [comment]
I don't think it's possible to detect if a middle or right click means that the link was followed, but it's a good question whether we should track them regardless. Marking this issue for review next week.

**Comment by patmmccann** [comment]
Committee confirms, track all clicks, thanks for the bug report!

**Comment by chakersaloumi** [comment]
great, thank you!!
