### ISSUE TITLE
Ad markup with <!DOCTYPE html> fails to render on web

### ISSUE THREAD

**Issue by vraybaud** [prebid/prebid-universal-creative#209]
**Describe the bug**
If an ad markup contains the <!DOCTYPE html> preamble, it silently stops parsing and only the HTML up to that point is inserted into the document. There is a old issue linked to that : https://github.com/prebid/prebid-universal-creative/issues/134

**To Reproduce**
From prebid server return any ad markup with <!DOCTYPE html> (eg. <!DOCTYPE html><p>test<p>) and inspect the DOM in chrome://inspect.
Removing the doctype preamble renders the ad as expected.

**Expected behavior**
Render the ad with doctype correctly as on the web with prebid.js.

**Screenshots**
With version 1.14.2: 
![image](https://user-images.githubusercontent.com/11096082/233045112-923bcb99-9186-4575-a30b-8f77312f692b.png)

With version 1.15.0:
![image](https://user-images.githubusercontent.com/11096082/233045411-ff8c356b-764c-4106-bc93-33e292807d99.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by dgirardi** [comment]
Just noticed this:

 > From prebid server 

is "server" important - are you using AMP or another environment without Prebid.js?

**Comment by bretg** [comment]
Spent way too long digging into this and found something possibly interesting:

At least in the AMP and App workflow, the PUC is forcing in a comment at the very beginning of the creative, so when DOCTYPE is specified, it looks like this:

```
<!--Creative 1111 served by Prebid.js Header Bidding--><!DOCTYPE html><img src="https://files.prebid.org/creatives/prebid300x250.png">
```
Maybe it's invalid HTML to have a comment before the DOCTYPE?

**Comment by dgirardi** [comment]
It turns out this is a regression to exactly the same issue #134 - affecting app/amp/mobile but not web as far as I can tell.
