### ISSUE TITLE
Not rendering in PB 1.15

### ISSUE THREAD

**Issue by mercuryyy** [prebid/prebid-universal-creative#21]
@mkendall07  please see attached image
Not rendering in PB 1.15

![screen shot 2018-07-01 at 10 02 47 pm](https://user-images.githubusercontent.com/7463132/42141962-a6ac2348-7d7a-11e8-9a3b-02975d1a003e.png)
![screen shot 2018-07-01 at 10 04 34 pm](https://user-images.githubusercontent.com/7463132/42141991-d7ab8880-7d7a-11e8-9ee2-1f92c2ed41bf.png)

**Comment by mercuryyy** [comment]
I think its because 

for (i = 0; i < 10; i++)

should probably be

for (var i = 0; i < 10; i++)

Since you have use strict"; in the dist file

**Comment by mkendall07** [comment]
thanks for the bug report! Opened a PR for the fix.
