### ISSUE TITLE
cookieSync code redundant; too noisy

### ISSUE THREAD

**Issue by patmmccann** [prebid/prebid-universal-creative#212]
**Describe the bug**

**To Reproduce**
https://github.com/prebid/prebid-universal-creative/blob/master/src/cookieSync.js is far too noisy and shares lots of code with https://github.com/prebid/prebid-universal-creative/blob/master/src/cookieSyncWithConsent.js . They should not have code copy pastes and they should not console log so much. 

load_cookie_with_consent.html and load_cookie.html should source the same js and be identical in any other way.

**Comment by patmmccann** [comment]
Bumping priority to high as cookie sync without consent getting flagged more often by community

**Comment by dgirardi** [comment]
What is getting flagged? Is there a bug, or a nice to have?

I'd be parsimonious with updating these as they are hard to test and harder to deploy. It's not clear to me that we even can do a comprehensive deployment - see https://github.com/prebid/prebid-universal-creative/issues/186

**Comment by patmmccann** [comment]
this is pretty big issue, we need both load-cookie htmls to have gpp consent

**Comment by patmmccann** [comment]
a publisher using the software was contacted by a government recently
