### ISSUE TITLE
Updated Creative template clarifications for DFP

### ISSUE THREAD

**Issue by Guilemon** [prebid/prebid-universal-creative#27]
I observed the creative template is different from the one mentioned here: http://prebid.org/dev-docs/show-prebid-ads-on-amp-pages.html#html-creative

Please clarify the following:
```javascript 
  // if DFP, use this param
  ucTagData.targetingMap = %%PATTERN:TARGETINGMAP%%;
  // if not DFP, use these params
  ucTagData.adId = "%%PATTERN:hb_adid%%";
  ucTagData.cacheHost = "%%PATTERN:hb_cache_host%%";
  ucTagData.cachePath = "%%PATTERN:hb_cache_path%%";
  ucTagData.uuid = "%%PATTERN:hb_cache_id%%";
  ucTagData.mediaType = "%%PATTERN:hb_format%%";
  ucTagData.env = "%%PATTERN:hb_env%%";
  ucTagData.size = "%%PATTERN:hb_size%%";
```

I'm using prebid server with amp creative setup in dfp, should i just add ` ucTagData.targetingMap = %%PATTERN:TARGETINGMAP%%;` parameter in my creative template and omit out the 'not DFP' ones?

**Comment by Guilemon** [comment]
just copy the complete template in dfp.

`ucTagData.targetingMap` gets the bidding information while the cache host and cache path needs to be hard coded as per the prebid cache host.  uuid parameter gets `hb_cache` value.

Also while running this, `ucTag is undefined` error gets logged in console and no creative gets rendered...

**Comment by misterhegde** [comment]
i know this was 4 years ago, but any solution for the Undefined?

**Comment by Guilemon** [comment]
in  above case the latest file in jsdelivr cdn didn't have `ucTag` as global variable. it was using an older version of the creative js. This was solved by the prebid team
