### ISSUE TITLE
Will work with Prebid 0.3.4?

### ISSUE THREAD

**Issue by lanceloti** [prebid/prebid-universal-creative#7]

**Comment by mkendall07** [comment]
I believe it should, but not sure if we have tested it yet.

**Comment by lanceloti** [comment]
I'm missing something... renderAd is not called. I'm testing with DFP Safeframe on desktop. Should I pass macros like '%%PATTERN:url%%'?

**Comment by mkendall07** [comment]
@lanceloti 
sorry for the delay. Did you get it working?
'%%PATTERN:url%%'? is passed automatically from DFP so you shouldn't have to do anything.

**Comment by lanceloti** [comment]
@mkendall07 I'm wating a "how to" section. 
Currently I'm doing this:
npm install
gulp build
put dist/creative.js into a DFP 3rd party creative
RenderAd not called, no error. Adslot still blank.

**Comment by mkendall07** [comment]
@lanceloti 
Do you have a test page?

**Comment by lanceloti** [comment]
Hi @mkendall07 
I'm testing here: https://maringapost.com.br/ads.php

**Comment by lanceloti** [comment]
I found this code on prebid documentation and it solved my doubt.

</script>
    <script>
    var adId = "%%PATTERN:hb_adid%%";
    var cacheHost = "%%PATTERN:hb_cache_host%%";
    var cachePath = "%%PATTERN:hb_cache_path%%";
    var uuid = "%%PATTERN:hb_cache_id%%";
    var mediaType = "%%PATTERN:hb_format%%";
    var pubUrl = "%%PATTERN:url%%";

    try {
        pbjs.renderAd(document, adId, {
            cacheHost: cacheHost,
            cachePath: cachePath,
            uuid: uuid,
            mediaType: mediaType,
            pubUrl: pubUrl
        });
    } catch (e) {
        console.log(e);
    }
</script>
