### ISSUE TITLE
Update browserstack tests to run on supported browser versions

### ISSUE THREAD

**Issue by Fawke** [prebid/prebid-universal-creative#85]
**Describe the bug**
The command `gulp test --browserstack` command runs locally but throws an error when run inside Circle CI environment.

**To Reproduce**
Trigger a build in Circle CI by meaning of pushing a commit or manually trigger a build (if you've access) on circle ci for this repo.

**Expected behavior**
Circle CI, especially the last step *Browserstack Testing* should pass.

**Error**
```
Firefox 68.0.0 (Windows 10.0.0) LOG LOG: 'xhr error', null, ''
Error: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.6.3</center>
</body>
</html>

    at IncomingMessage.<anonymous> (/Users/jsnellbaker/git/prebid-universal-creative/node_modules/browserstack/lib/client.js:74:8)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1085:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
**Desktop (please complete the following information):**
 - OS: Mac OS 10.15
 - Browser: Chrome

**Comment by dgirardi** [comment]
CircleCI now is running, and usually succeeding, browserstack tests - the error above looks like possibly a temporary browserstack outage.

However, the tests do neet work; at least we should bring the browsers we test in line with pbjs.
