### ISSUE TITLE
Native asset replacement does not replace all occurrences of searchString in HTML

### ISSUE THREAD

**Issue by beth92** [prebid/prebid-universal-creative#87]
**Describe the bug**
When a native template contains multple usages of the same native asset, the native tracker script only replaces the first occurrence with the asset value. This leaves the remaining occurrences with the placeholder values which could break the ability of the native ad to function (i.e. invalid click-through URL).

**To Reproduce**
Trivial example of a native template which would have this problem: 
```html
<div style='overflow: hidden;'>
  <!-- this link works -->
  <a class='thumbnail' href="%%CLICK_URL_UNESC%%%%PATTERN:hb_native_linkurl%%" target="_blank" class="pb-click" pbAdId="%%PATTERN:hb_adid%%"><img src="%%PATTERN:hb_native_image%%"/></a>
  <div class='cta'>
    <!-- this one doesn't -->
    <a href="%%CLICK_URL_UNESC%%%%PATTERN:hb_native_linkurl%%" target="_blank" class="pb-click" pbAdId="%%PATTERN:hb_adid%%">%%PATTERN:hb_native_cta%%</a>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/prebid-universal-creative@latest/dist/native-trk.js"></script>
<script>
  let pbNativeTagData = {};
  pbNativeTagData.pubUrl = "%%PATTERN:url%%";
  window.pbNativeTag.startTrackers(pbNativeTagData);
</script>
```

**Expected behavior**
For the native template, I'd like multiple clickable elements. 

**Additional context**
I created a PR which helped me solve the problem on our fork: #86
This includes a test case which hopefully makes it clear what the intended behaviour should be.

**Comment by bretg** [comment]
This was resolved with #86 - thanks.
