### ISSUE TITLE
Error adding Universal Creative in Google Ad Manager

### ISSUE THREAD

**Issue by cliffordh** [prebid/prebid-universal-creative#90]
**Describe the bug**
I have copied the Universal Creative code and pasted as a new Creative, but I'm receiving this message: "Sorry, we don't recognize this tag. If you want to track clicks via Google Ad Manager and avoid counting discrepancies, you must insert the macros manually. Please contact the tag provider for directions on where to place the macros."

I am new to Prebid and Google Ad Manager in general. Assistance is welcome.

**Comment by bretg** [comment]
Unfortunately, Prebid Universal Creative doesn't support click tracking. You can ignore GAM's warning message -- impressions should still appear. Click reporting will need to be done within the context of the SSP/DSP.

Note that supporting click tracking is a large task that would require a common convention across SSPs/DPSs. It's something that's certainly been discussed, but there's no committed timeline.
